# docker-compose.yml
version: '3.8'

services:
  # Aplicación OWL Frontend
  owl-app:
    build:
      context: ./owl-app
      dockerfile: Dockerfile
    container_name: sap-owl-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./owl-app/src:/app/src
      - ./owl-app/static:/app/static
    environment:
      - NODE_ENV=development
      - API_GATEWAY_URL=http://api-gateway:8000/api
      - SAP_SERVICE_LAYER_URL=https://host.docker.internal:50000/b1s/v1
    depends_on:
      - api-gateway
      - redis
    networks:
      - sap-owl-network

  # API Gateway (Python FastAPI)
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: sap-owl-api
    ports:
      - "8000:8000"
    volumes:
      - ./api-gateway/app:/app/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/amortization_db
      - REDIS_URL=redis://redis:6379/0
      - SAP_SERVICE_LAYER_URL=https://host.docker.internal:50000/b1s/v1
      - JWT_SECRET_KEY=your-super-secret-jwt-key-here
    depends_on:
      - postgres
      - redis
    networks:
      - sap-owl-network

  # Base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: sap-owl-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=amortization_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sap-owl-network

  # Redis para caché y sesiones
  redis:
    image: redis:7-alpine
    container_name: sap-owl-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sap-owl-network

  # Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    container_name: sap-owl-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - owl-app
      - api-gateway
    networks:
      - sap-owl-network

  # Servicio de monitoreo (opcional)
  monitoring:
    image: prom/prometheus
    container_name: sap-owl-monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - sap-owl-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:

networks:
  sap-owl-network:
    driver: bridge
