# .github/workflows/dependency-update.yml
name: Dependency Update

on:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6 AM
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Update npm dependencies
      working-directory: ./owl-app
      run: |
        npm update
        npm audit fix

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Update Python dependencies
      working-directory: ./api-gateway
      run: |
        pip install --upgrade pip pip-tools
        pip-compile --upgrade requirements.in
        pip install -r requirements.txt

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Automated dependency updates'
        body: |
          This PR contains automated dependency updates.
          
          Please review the changes and ensure all tests pass before merging.
        branch: dependency-updates
        delete-branch: true